### ISSUE TITLE
إضافة تفاسير القرآن وترجمات معانيه، ونصه بالرسم الإملائي

### ISSUE THREAD

**Issue by noureddin** [Mohamed-Nagdy/Hadith-Books-Json#1]
<div dir="rtl">

السلام عليكم ورحمة الله وبركاته.

جزاك الله خيرا على هذا المستودع القيم، ونفعنا الله وإياكم به.

لديّ اقتراحان وأستطيع أن أساعد في تطبيقهما بالصورة التي تراها مناسبة.

1. **إضافة نص القرآن الكريم بالرسم الإملائي غير المشكول (وربما المشكول أيضا) لتسهيل البحث (أو لأي غرض آخر لا&nbsp;يناسبه الرسم العثماني).**

    لا أدري ما الصيغة المناسبة؛ ربما قائمة أخرى بجوار `verse` في ملف كل سورة، مثل الأحاديث؟

    أحب أيضا أن أفهم قصدك من العبارة «إن شاء الله مستقبلا سيتم إضافة كل الآيات كملف لاستخدامها في البحث» التي كتبتها في ملف `README`، فربما أستطيع المساعدة في تنفيذها.

    أقترح استخدام: [القرآن الكريم/النص المجرد من ويكي مصدر](https://ar.wikisource.org/wiki/القرآن_الكريم/النص_المجرد).

    سؤال جانبي مرتبط: لماذا `verse` قاموس وليس قائمة؟ جميع السور تبدأ بالبسملة والتي مفتاحها `verse_0` حتى في الفاتحة، عدا التوبة التي تبدأ من `verse_1` بغير بسملة. ربما الأفضل فصل البسملة عن جميع السور (عدا الفاتحة، لأنها آيتها الأولى)، وإضافة attribute منفصلة لكل سورة توضح إمكان بدئها بالبسملة من عدمه؟ هذا ما يفعله مشروع [Quran-Data](https://github.com/alif-type/quran-data) مثلا (في ملف [meta.txt](https://github.com/alif-type/quran-data/blob/master/quran/meta.txt)).

    أو على الأقل جعل بسملة الفاتحة هي `verse_1`، فهي بالفعل آيتها الأولى.

2. **إضافة كتب التفاسير والتراجم للقرآن الكريم.**

    [برنامج آيات الحاسوبي](https://quran.ksu.edu.sa/ayat/) يأتي محمّلا بكتب تفاسير وتراجم، في صورة قواعد بيانات SQLite. أستطيع تحويلها إلى JSON بالصيغة التي تراها مناسبة.

    كل واحدة منها جدول واحد به أربعة قيم لكل آية: رقم الآية من بداية المصحف (١-٦٢٣٦)، رقم السورة (١-١١٤)، ورقم الآية داخل السورة، وخانة واحدة نصية للتفسير أو الترجمة.  عدا كتابين: التفسير الإنجليزي: تفهيم القرآن للمودودى، والتفسير الروسي؛ كلاهما يسجّلان الترجمة والتفسير في خانتين منفصلتين.

يمكننا كذلك إضافة المزيد من المعلومات عن السور، مثل ترجمة اسمها إلى الإنجليزية، وترتيب نزولها، وربما معلومات أخرى مثل عدد كلماتها وحروفها كموقع&nbsp;[equran.me](https://equran.me/read-1.html).

**Comment by Mohamed-Nagdy** [comment]
السلام عليكم 
بالنسبة للحل الخاص بال verse 
لم افهم المقصد
بالنسبة لإضافة الآيات مستقبلا ف ان شاء الله سيتم اضاف آيات القرآن كاملة بالترتيب التالي
رقم الآية في القرآن
رقم الآية في السورة
اسم السورة
رقم الصفحة
الجزء
الحزب
هل سجدة ام لا
والآية بتشكيل وبدون تشكيل  ان شاء الله
بالنسبة للقرآن كتفسير ف انا لم ارد اضافته للشك في صحته ف إذا كان ما تتحدث عنه موثوق في صحته ارسله لي وسأقوم برفعه ان شاء الله واضافته

**Comment by noureddin** [comment]
<div dir="rtl">

جزاك الله خيرا. وأعتذر لتأخري، فقد احتجت أن أبحث أكثر قبل أن أرد.


1. **بالنسبة للتفاسير والتراجم،** فهي من [برنامج آيات الحاسوبي](https://quran.ksu.edu.sa/ayat) مباشرةً (من [مشروع المصحف الإلكتروني بجامعة الملك سعود](https://quran.ksu.edu.sa))، فأظنه مصدرًا موثوقًا بإذن الله. ولكني أردت أيضا أن أوفر طريقة واضحة لتنزيلها منه مباشرةً، حتى تطمئن (والمستخدمون) إلى موثوقيتها.

    [دليل تنزيل التفاسير والتراجم من آيات وتحويلها إلى JSON](https://gist.github.com/noureddin/36742c87431e4312957b8e42d28ff9f4). إن أحببت، أستطيع أن أقوم بهذه المهمة وأرفع المجلدين المحوّلين (`tafasir` و`tarajem`) في PR لهذا المستودع. ولكني أحب أن أعرف رأيك أولا.

    وأثناء إعدادي لهذا الدليل، لاحظت أن ملفات الكتب المرفقة مع نسخة لينكس من البرنامج مختلفة عن وندوز، فقارنتها ووجدت أن الاختلافات هي تصليحات أضيفت في ملفات وندوز ولم تصل إلى ملفات لينكس، والاختلاف الوحيد الآخر أن عند عدم وجود تفسير لإحدى الآيات، فإن ملفات لينكس استخدمت إحدى صيغ العبارة «لا يوجد تفسير لهذه الآية» في حين أن ملفات وندوز تركت التفسير فارغا (تحديدا: `<p></p>`).  
ثم ذهبت إلى موقع البرنامج مرة أخرى، ووجدت أن بالإمكان تنزيل الكتب منفردة من [صفحة التنزيلات](http://quran.ksu.edu.sa/ayat/?pg=patches)، فقارنتها أيضا بالملفات المرفقة مع نسخة وندوز، ووجدت أيضا أن نسخة وندوز متقدمة عنها في التصليحات.  
ثم قمت بتزيل نسخة ماك أيضا للمقارنة، فوجدت أنها مطابقة لملفات نسخة لينكس.  
ثم قمت بتنزيل نسخة أندرويد ووجدت أنها لا تحمل التفاسير والتراجم معها، فأظنها تنزل الملفات المنفصلة من موقع البرنامج.  
لم أحاول تنزيل نسخة آيفون، ولم أقارن نسخة الوب.

    الخلاصة: أظن أن الأخطاء إن وُجدت فهي قليلة بإذن الله، وبرنامج آيات مشهور ومعروف. ويمكن الإشارة في ملف README الخاص بمجلد التفاسير والتراجم أنها مأخوذة من برنامج آيات نسخة وندوز.

    ولكني مع ذلك أحببت أن أبحث عن مصادر إضافية. فوجدت:

    - موقع [التفسير](https://www.altafsir.com/indexArabic.asp). يقول أن كل تفسير أُدخل كتابةً (وليس مسحا) «ودقق ثلاث مرات على الأقلّ من قبل فرق مختلفة من العلماء». لم أجد طريقة مباشرة لتنزيل شيئا من محتواه، ثم وجدت أن [شروط استخدامه](https://www.altafsir.com/TafsirTerms.asp) تمنع حتى محاولة فعل ذلك (النقاط c و g في الفصل الأول «Accessing the Sites»).

    - [المكتبة الشاملة (قسم التفاسير)](https://shamela.ws/index.php/category/127). هل هي مناسبة؟

    - موقع [تنزيل](http://tanzil.net)، والذي يتيح النص القرآني ب[عدة صيغ](http://tanzil.net/docs/quran_text_types) (عثماني، عثماني بتشكيل أقل، إملائي بأربعة مستويات من التشكيل). لديهم صفحة [موارد](http://tanzil.net/docs/resources)، والتي تشير إلى صفحة [التفاسير والتراجم](http://tanzil.net/trans/) (متاح الجلالين والميسر فقط للغة العربية)، والتي تشير إلى [مصدر هذه الكتب](http://tanzil.net/wiki/Translations_Resources)، فوصلت إلى&hellip;

    - موقع [مجمع الملك فهد لطباعة المصحف الشريف](https://qurancomplex.gov.sa)، وهو الذي أصدر مصحف المدينة النبوية الشائع. هم أيضا يصدرون التفسير الميسر. فأظن أن هذا هو أدق المصادر وأكثرها موثوقية للتفسير الميسر. يمكن تنزيل التفسير الميسر (ونص المصحف بالرسم العثماني بعدة روايات، بل وصور المصحف بصيغة AI) من صفحة [خدمات مطوري برمجيات القرآن الكريم](https://qurancomplex.gov.sa/techquran/dev/). هذا أدق ما استطعت الوصول إليه.

        ووجدتهم أيضا يعملون على [ترجمة معاني القرآن الكريم](https://qurancomplex.gov.sa/kfgqpc-quran-translate/). لكني لم أجد أن بالإمكان تنزيل التراجم بصيغة نصية (غير PDF). (كان بحثي مركزا على التفاسير؛ إن أردنا إضافة التراجم كذلك، فيمكننا الوصول إلى العديد من المصادر الموثوقة الأخرى بإذن الله.)

2. **بالنسبة لـ«رقم الآية في القرآن» و«رقم الآية في السورة»،** فهذه المعلومات بالفعل في كل جدول من جداول كتب برنامج آيات. ومتاحة كذلك (والمزيد) من [موقع تنزيل](http://tanzil.net/docs/quran_metadata). أستطيع الوصول إلى مصادر أخرى إن شئت. 

3. **أما عن «الآية بتشكيل وبدون تشكيل»،** فهما متاحان بالفعل على ويكي مصدر: [القرآن الكريم/النص المشكول](https://ar.wikisource.org/wiki/القرآن_الكريم/النص_المشكول) و[القرآن الكريم/النص المجرد](https://ar.wikisource.org/wiki/القرآن_الكريم/النص_المجرد)، وتحويلهما إلى JSON أو غيرها يسير إن شاء الله. ومتاحان كذلك في [موقع تنزيل](http://tanzil.net/download/)، بأربعة مستويات للتشكيل في الرسم الإملائي.

4. **بالنسبة لـ`verse`،** فقصدت شيئين، أولهما هو أنها قاموس وليست قائمة، مثلا في ملف [سورة الإخلاص](https://github.com/Mohamed-Nagdy/Quran-App-Data/blob/783c1c6a2b6ce94f07fa4f956e4f3a18fdbe391e/Quran%20Suras/surah_112.json#L4-L10) نجد:

    <div dir="ltr" align="left">
    
    ```json
        "verse": {
            "verse_0": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            "verse_1": "قُلْ هُوَ ٱللَّهُ أَحَدٌ",
            "verse_2": "ٱللَّهُ ٱلصَّمَدُ",
            "verse_3": "لَمْ يَلِدْ وَلَمْ يُولَدْ",
            "verse_4": "وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ"
        },
    ```

    </div>
    
    مع أني أتوقع:

    <div dir="ltr" align="left">
    
    ```json
        "verse": [
            "قُلْ هُوَ ٱللَّهُ أَحَدٌ",
            "ٱللَّهُ ٱلصَّمَدُ",
            "لَمْ يَلِدْ وَلَمْ يُولَدْ",
            "وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ"
        ],
    ```
    
    </div>
    
    وثانيهما هو البسملة: البسملة هي الآية الأولى من سورة الفاتحة (وجزء من آية في سورة النمل)، وجميع السور يجب أن تبدأ بالبسملة، عدا التوبة (وكذلك الفاتحة، لأن البسملة آية منها بالفعل).
    
    ولتوضيح الأمر أكثر: عدد آيات الفاتحة سبعة (منها البسملة)، ونجد أن عدد عناصر `verse`ـها هو سبعة فعلا. والإخلاص عدد آياتها أربعة، لكن عدد عناصر `verse`ـها هو خمسة! كُسر الاتساق بين عدد الآيات وعدد عناصر `verse`.

    وليس هذا فحسب، بل إن آيات [الفاتحة](https://github.com/Mohamed-Nagdy/Quran-App-Data/blob/783c1c6a2b6ce94f07fa4f956e4f3a18fdbe391e/Quran%20Suras/surah_1.json#L4-L12) مختلفة عن المصحف، فالآية الأخيرة هي السابعة، وليست السادسة كما يقول الملف، وآية «الحمد لله رب العالمين» هي الآية رقم اثنين، ولكن الملف يقول أنها الآية رقم واحد.

    أرى حلين لهذه المشكلة (أو فعليا أربعة حلول):

    1. حذف البسملة من بداية جميع السور (عدا الفاتحة)، وإضافة attribute إلى كل سورة توضح هل يمكن بدء هذه السورة بالبسملة أم لا. هذا ما يفعله مثلا مشروع [Quran-Data](https://github.com/alif-type/quran-data/blob/master/quran/meta.txt) (لاحظ الصفر في الخانة الثالثة أمام الفاتحة والتوبة). ويمكننا حينئذٍ تحويل `verse` من قاموس إلى قائمة، أو بدء القاموس دائما بـ`verse_1`.

    2. الإبقاء على `verse` كقاموس، لكن جعل البسملة (الإضافية) هي  دائما`verse_0`. هذا ما تفعله بالفعل في جميع السور، عدا الفاتحة؛ بسملة الفاتحة هي الآية الأولى منها، وليست «الآية صفر». فهذا الحل يتطلب تعديلا واحدا هو جعل بسملة الفاتحة `verse_1` ودفع الآيات الأخرى للأمام خطوة (فتكون الآية الأخيرة هي السابعة (وهو الترقيم المطابق للمصحف) وليست كما هي الآن، الآية السادسة)،

        فنجد وقتئذٍ أن عدد الآيات هو نفسه رقم الآية الأخيرة في جميع السور، وأن «الآية صفر» يمكن حذفها (مثلا) أو تنسيقها بشكل مختلف أو معاملتها معاملة خاصة حسب التطبيق، مثلا عند [الاستماع إلى الآيات](https://everyayah.com)، الآية صفر من أيّة سورة ستُترجم إلى الآية الأولى من الفاتحة. لاحظ أن في هذا المثال (الاستماع إلى الآيات)، الترقيم الحالي لآيات الفاتحة سيتطلب معاملة خاصة لها، لاختلاف رقم الآية المسجّل (في ملف الـJSON) عن رقم الآية الفعلي.

        يمكن تنفيذ هذا بقائمة أيضا: العنصر صفر إما يحمل البسملة أو يحمل القيمة `null` (أو النص الفارغ `""`، لا أدري أيهما أنسب)، والعنصر واحد يحمل الآية رقم واحد، وهكذا. هكذا نحافظ على ترقيم الآيات بدءا من الواحد، ونخبر التطبيق المستخدِم عن البسملة بغير attribute إضافية.


    تلخيص هذه الحلول الأربعة:

    1. حذف البسملة من بداية جميع السور عدا الفاتحة، وإضافة attribute بقيمة `true` لجميع السور، وبقيمة `false` للفاتحة والتوبة (أو العكس).

    2. نفس الحل السابق + تحويل `verse` من قاموس إلى قائمة.

    3. زيادة رقم `verse` في جميع آيات سورة الفاتحة فقط.

    4. تحويل `verse` جميع السور إلى قائمة (وبها البسملة في العنصر الأول)، وإضافة `null` (أو `""`؟) قبل العنصر الأول في الفاتحة والتوبة.

***

بالمناسبة، على GitHub، تستطيع بدء أي محتوى Markdown عربي (ملف أو تعليق) بكتابة

<div dir="ltr" align="left">

```html
<div dir="rtl">
```

</div>

متبوعًا بسطر فارغ، ثم استخدام Markdown كما تشاء. وسيظهر النص العربي مضبوطا حتى عند خلطه بكلمات إنجليزية. ولا حاجة لغلقها (‪`</div>`‬) في نهاية الملف أو التعليق. :smiley:

**Comment by Mohamed-Nagdy** [comment]
<div dir="rtl">

انا بصراحة مش قادر ارد عليك بعد المجهود العظيم اللي انت عملته ده واستفدت منك جدا جدا بالمواقع والمعلومات الجبارة اللي حضرتك حبتاه ف حضرتك تقدر تضيف اللي تقدر عليه ويكبر ال repo ده ويكون شامل وجامع لكل الداتا اللي اي حد ممكن يحتاجها لتطبيق او موقع اسلامي وربنا يجعله في ميزان حسناتنا جميعا يارب

**Comment by noureddin** [comment]
<div dir="rtl">

أعتذر مجددا على تأخر ردي.

> ربنا يجعله في ميزان حسناتنا جميعا يارب

جزاك الله خيرا، ونفعنا به وجعل عملنا هذا خالصا لوجهه الكريم.

> انا بصراحة مش قادر ارد عليك بعد المجهود العظيم اللي انت عملته ده واستفدت منك جدا جدا بالمواقع والمعلومات الجبارة اللي جبتها

لقد بحثت على الإنترنت وحسب. 😅 وأكثر من نصف تعليقي السابق كان معلومات جديدة بالنسبة لي، وقد استفدت شخصيا كثيرا وتعلمت كثيرا أثناء إعدادي إياه. ولا داعٍ لكلمة «حضرتك». 😄

> تقدر تضيف اللي تقدر عليه ويكبر ال repo ده ويكون شامل وجامع لكل الداتا اللي اي حد ممكن يحتاجها لتطبيق او موقع اسلامي

أتفق معك، فوجود هذه الموارد القيّمة في مكان واحد يسهّل كثيرا على المطورين، بل وقد يلهمهم أفكار تطبيقات لم تكن لتأتيهم لولا أن تيسّرت لهم هذه الموارد القيّمة. جزاك الله خيرا على بدء هذا المستودع وملئه بهذا المحتوى القيم.

أرسلت طلب ضم (#4). ووصفه مفصّل نسبيا، لكن خلاصة ما فيه ما يلي:

1. [إضافة التفاسير والتراجم](https://github.com/noureddin/Quran-App-Data/tree/main/Tafaseer) من برنامج آيات، مع الإشارة إلى تراجم تنزيل وقائمة مواردهم والتفسير الميسر من مجمع الملك فهد.
2. [إضافة الـmetadata](https://github.com/noureddin/Quran-App-Data/tree/main/quran_metadata) من تنزيل، مع جعلها تتبع نفس الصيغة المستخدمة في ملفي الأجزاء والسور في هذا المستودع.
3. تصحيح ترقيم سورة الفاتحة مؤقتا (انتظر نقطة `verse` بالأسفل).
4. إضافة وصف لملفات التفاسير ولملفات الـmetadata ومحتوياتها.

ولدي سؤال: في [ملف السور][suar]، حقل `page` مفهوم أنه صفحة السورة (الآية الأولى منها) في مصحف المدينة، لكن ماذا يعني حقل `pages` (بالـ`s`)؟ لا يبدو لي أنه يحمل عدد صفحات السورة في مصحف المدينة، بل صفحة بداية السورة (أيضا) لكن في مصحف آخر غير مصحف المدينة، نظرت إلى مصحف الأزهر (طبعة الشمرلي) لكني وجدته مختلف عن هذه الأرقام. فلم أستطع شرح هذا الحقل في README المجلد. فما هو؟

أقترح كذلك:

1. تحويل جميع الأرقام إلى أرقام فعلية، وليست أرقاما في صورة strings،  (أي `1` وليس `"1"` أو `"001"` أو `"verse_1"`).

2. إضافة ملف (Markdown) لجمع الموارد المختلفة وتنظيمها، مثلا صفحة [الموارد على موقع تنزيل][tzrsc]، صفحة [خدمات المطورين على موقع مجمع الملك فهد][kf]، موقع [المكتبة الشاملة][sh]، موقع [صوتيات آيات القرآن][mp3]، إلخ. مع وصف شامل لكن قصير عن كل مورد.

[suar]: https://github.com/Mohamed-Nagdy/Quran-App-Data/blob/main/surah.json
[tzmd]: http://tanzil.net/res/text/metadata/quran-data.js
[tzrsc]: http://tanzil.net/docs/resources
[tztypes]: http://tanzil.net/docs/quran_text_types
[tztxt]: http://tanzil.net/download/
[kf]: https://qurancomplex.gov.sa/techquran/dev/
[sh]: https://shamela.ws/rep.php
[mp3]: https://everyayah.com/
[wst]: https://ar.wikisource.org/wiki/القرآن_الكريم/النص_المشكول
[wsp]: https://ar.wikisource.org/wiki/القرآن_الكريم/النص_المجرد
[asmaa]: https://ar.wikipedia.org/wiki/أسماء_الله_الحسنى

3. `verse`: اقترحت أربعة حلول، هل ترى أن أحدها مناسب أم تقترح حلا آخر؟

    اقتراحي الثالث يتطلب أقل تعديلات (تعديل مفاتيح سورة الفاتحة فقط)، لكن الرابع هو الأقرب إلى أسلوب metadata تنزيل؛ فجميع قوائم [metadata تنزيل][tzmd]، بلا استثناء (حتى قائمة السجدات)، تهمل العنصر رقم صفر، مما يجعل قوائمها فعليا ‎1-based.

    بحثت كثيرا ولازلت لا أدري أيهما الأنسب: استخدام `null` أم `""` في الاقتراح الرابع (في العنصر رقم صفر من الفاتحة والتوبة، بدلا من البسملة الإضافية). أميل إلى `""` إن اخترتَ هذا الاقتراح.

    لكني عموما أحبّذ تحويلها إلى قائمة (الاقتراح الثاني أو الرابع).

4. إضافة نص القرآن الكريم بالرسم الإملائي، بالتشكيل وبدونه. لم أضفه بعد لأني أقترح إضافته بنفس شكل قائمة `verse` بالضبط، وبجوارها في نفس ملف السورة، فأنتظر قولك في الأمر السابق (`verse`) وكذلك في مكان إضافته.

    موقع تنزيل يوفّر [عدة صيغ][tztypes] للرسم الإملائي، منها المشكول طبقا لقواعد الإملاء الحديثة، والخالي من التشكيل. قارنتهما (Simple وSimple Clean) مع المتاح عبر ويكي مصدر ([المشكول][wst] و[المجرد][wsp])، فلاحظت الفروق التالية:

    1. اختلاف الرخصة:

        - ويكي مصدر يستخدم CC BY-SA 3.0، بغير قيود إضافية. (الإشارة إلى المصدر وحسب.)

        - تنزيل يستخدم CC BY 3.0 مع فرض الإشارة إلى الموقع دوما وكذلك إلى الـ"copyright notice". (اقرأ الترخيص في [صفحة التنزيل][tztxt].) لا أجد في فرض نسخ الـ"copyright notice" حرجا لأنه يفرض فعل ذلك في الملف الذي يضم النص فقط (أي الكود المصدري؛ لا قيود على الناتج أو الواجهة الرسومية)، أما نقطة الإشارة إلى الموقع بوضوح للمستخدمين، رغم إني أؤيدها وأفهم المنطق من ورائها، إلا أني لست متأكدا أن جميع التطبيقات سيناسبها هذا. إلا إن كان فهمي خاطئا لرخصتهم.

    2. اختلاف في رسم ثلاث كلمات، وهذا هو الاختلاف الوحيد في الرسم:

        |الموضع|تنزيل الإملائي|ويكي مصدر الإملائي|النص بالرسم العثماني|
        |--:|--:|--:|--:|
        |سورة طه، الآية&nbsp;٩٤|قَالَ يَا ابْنَ أُمَّ&hellip;|قَالَ يَبْنَؤُمَّ&hellip;|قَالَ يَبْنَؤُمَّ&hellip;|
        |سورة القلم، الآية&nbsp;٦|بِأَيْيِكُمُ الْمَفْتُونُ|بِأَيِّكُمُ الْمَفْتُونُ|بِأَييِّكُمُ ٱلْمَفْتُونُ|
        |سورة الجن، الآية&nbsp;١٦|وَأَنْ لَوِ اسْتَقَامُوا&hellip;|وَأَلَّوِ اسْتَقَامُوا&hellip;|وَأَلَّوِ ٱسْتَقَٰمُوا۟&hellip;|

    3. في النص المشكول، بالإضافة إلى اختلاف الرسم السابق، اختلف ترتيب الشدة مع الحركة: كتب تنزيل الشدة دائما قبل الحركة، وهذا هو الشائع في رأيي، أما ويكي مصدر فكتبها *بعد* الحركة. لا فرق ظاهر بين الاثنين، لكن إن احتجت التعامل مع النص على مستوى المحارف (characters)، فستحتاج أن تعرف هذا. احتجتُ إلى تبديل موضع الشدة مع الحركة في نص ويكي مصدر حتى أقارنه مع نص تنزيل.

    لاحظ أن الاثنين يتّبعان قواعد الإملاء الحديثة قدر الإمكان، بغض النظر عن رسم الكلمة في الرسم العثماني (باستثناءات قليلة مثل كتابة التاء المفتوحة كالرسم العثماني، مثل «رحمت ربك» و«امرأت فرعون»).

    أترك لك اختيار أحد المصدرين أو غيرهما. 😃 وأستطيع تحويله إلى الصيغة المناسبة بعد الاتفاق على نقطة `verse` السابقة وتحديد مصدر النص.

    أيضا أحب أن أذكّر بأن الاثنين يطلبان الإشارة إلى المصدر. والأفضل الإشارة إلى المصدر حتى وإن لم يطلباه. فسأشير إلى مصدر النص في ملف `README` الخاص بمجلد السور (بفرض أن النص الإملائي سيوضع في ملف كل سورة بجوار النص العثماني). لذا أظن أيضا أن من المناسب ذكر مصدر النص العثماني كذلك. فما هو؟

لدي اقتراح آخر كذلك:

5. أسماء الله الحسنى:

    حاليا كل اسم له حقل واحد يحمل الاسم باللغة العربية ومكتوبا بالتشكيل. أقترح إضافة:

    - الاسم باللغة العربية من غير تشكيل،
    - ترجمة صوتية للاسم،
    - ترجمة معنى الاسم إلى الإنجيزية (عدا «الله»، يُكتب «Allah»)، ويمكن إضافة أكثر من ترجمة مفصولة بـ`,` مثلا،
    - شرح معنى الاسم بالعربية،
    - هل الاسم ثابت في القرآن أو السنة أم لا.

للنقطتين الأخيرتين، أرجو الإطلاع على مقالة [أسماء الله الحسنى على ويكيبديا][asmaa].

**Comment by moh21amed** [comment]
بارك الله فيكما انتم الاثنين
بس هل استخدام الداتا الخاصة ببرنامج ايات مصرح به ومفتوح المصدر ام ماذا ؟

**Comment by noureddin** [comment]
<div dir="rtl">

لا أجد شيئا في صفحة تنزيل تطبيق آيات عن ترخيص استخدام التفاسير والتراجم وحدها. مذكور فقط أن البرنامج (ككل) يمكن توزيعه للاستخدام الشخصي وغير التجاري.

لكن نافذة حول المشروع في صفحة التطبيق (التي لم ألاحظها إلا الآن)، تقول أن مصدر التراجم هو [موقع تنزيل](http://www.tanzil.net/trans)، ومصدر التفاسير هو [موقع المصحف](https://www.mosshaf.com).

ولكن موقع المصحف أيضا لا يوضّح وجود أي قيود على التفاسير.

**Comment by salamali** [comment]
جزاكم الله خيرا على هذا الجهد الكبير
أشكركم من قلبي
سأحاول استخدام هذه المعلومات في موقعي [القرآن الكريم](https://surahquran.com/) إن شاء الله تعالى
و سعيد جدا بتعاونكم معي
و أتشرف باخوة كرام أمثالكم

**Comment by Ehsan-M-A** [comment]
How are you?
I want someone to help me.

I want a repository for Quranic interpretations, such as Ibn Kathir's or Saadi's interpretations.

Thank you.

**Comment by noureddin** [comment]
@Ehsan-M-A: This repository has a number of interpretations (tafasir) and translations, at: <https://github.com/Mohamed-Nagdy/Quran-App-Data/tree/main/Tafaseer>; specifically, here are [Ibn Kathir's](https://github.com/Mohamed-Nagdy/Quran-App-Data/blob/main/Tafaseer/katheer.json), and [Saadi's](https://github.com/Mohamed-Nagdy/Quran-App-Data/blob/main/Tafaseer/sa3dy.json).
