### ISSUE TITLE
Extra Bassmalla

### ISSUE THREAD

**Issue by ahmed-nabil-elagder** [Mohamed-Nagdy/Hadith-Books-Json#10]
No need for extra Bassmalla

https://github.com/Mohamed-Nagdy/Quran-App-Data/blob/535ae53e7e4052cd59f184a7a50115a50ac5f0ff/Quran%20Suras/surah_97.json#L6

Hint:
I recommend to sync with the original repo (this issue fixed there)
https://github.com/semarketir/quranjson/commits/master/source/surah/surah_97.json
To be updated about fixes and enhancements.

**Comment by Mohamed-Nagdy** [comment]
it removed thank you
