### ISSUE TITLE
خطأ في أسماء النبي محمد صلي الله عليه وسلم

### ISSUE THREAD

**Issue by AbdallahElshinbary** [Mohamed-Nagdy/Hadith-Books-Json#2]
السلام عليكم ورحمة الله وبركاته
برجاء مراجعة صحة اسماء النبي محمد صلي الله عليه وسلم مثل "طه" و "يس" فهي حروف متقطعة وليست اسماء للنبي محمد صلي الله عليه وسلم

**Comment by Mohamed-Nagdy** [comment]
تم التعديل وإزالة الأسماء المذكورة 
وإذا عندك اي شك آخر او تعديل ف تفضل في اي وقت 
شكرا لك
