### ISSUE TITLE
استفسار

### ISSUE THREAD

**Issue by software-ace** [Mohamed-Nagdy/Hadith-Books-Json#5]
هل لديك خطة عمل للمشروع ؟
ان كان لديك يرجى اضافتها وتجزيئها ل tasks من قائمة projects
حتى يسهل المساعدة بهذا العمل

سابدأ بتصميم شاشات التطبيق باستعمال flutter ان كان يوجد اي تصميم تريد شي مشابه له ارجو وضعه هنا بالردود

**Comment by Mohamed-Nagdy** [comment]
السلام عليكم 
التطبيق موجود بالفعل على متجر جوجل اذا تحب تطلع عليه
[https://play.google.com/store/apps/details?id=com.quran_and_azkar.quran_and_azkar_app](url) 
وان شاء الله هنزله ك اوبن سورس مع الريبو ده علشان لو حد حابب يستفيد او يضيف له اي شئ

**Comment by software-ace** [comment]
جزاك الله خيرا
ما زلت افضل ان نعمله ب فلاتر ليكون متوفر على جميع المتاجر 
منتظر توفر السورس كود الحالي منك حتى ابدا العمل على تحويله ل تطبيق فلاتر

**Comment by Mohamed-Nagdy** [comment]
السورس كود فعليا معمول فلاتر لكن ماعنديش متجر على ابل علشان ارفعه عليه بس
