### ISSUE TITLE
رواية ورش

### ISSUE THREAD

**Issue by akram19-setif** [Mohamed-Nagdy/Hadith-Books-Json#7]
جزاك الله خيرا على هذا المجهود الطيب
و أسأل ان ينفع به
رواية ورش لو أضفتموها لكانت اكثر  نفعا
اعانكم الله

**Comment by Mohamed-Nagdy** [comment]
شكرا جزيلا لك وان شاء الله إن وجد اي مصدر لها سيتم اضافته وإذا كان لديك مصدر نتمنى مشاركتنا الاجر

**Comment by zahsadz** [comment]
في روايات مختلفة وبعدة صيغ
https://qurancomplex.gov.sa/techquran/dev/

**Comment by zahsadz** [comment]
> 
> 
> جزاك الله خيرا على هذا المجهود الطيب
> و أسأل ان ينفع به
> رواية ورش لو أضفتموها لكانت اكثر نفعا
> اعانكم الله
 https://qurancomplex.gov.sa/techquran/dev/
