### ISSUE TITLE
laravel app

### ISSUE THREAD

**Issue by elsayed85** [Mohamed-Nagdy/Hadith-Books-Json#8]
I create a simple laravel app using the data

https://github.com/elsayed85/quran
SQL data : 
https://drive.google.com/file/d/1kpwlqjRGwuRBUYIN9_v37oUmBFt-rQiW/view?usp=sharing
Video : https://youtu.be/7VvlBOINfjQ
Updated Video* : https://youtu.be/_jW3beDxppA

**Comment by Mohamed-Nagdy** [comment]
i think there is no sound in video but we are so glade i will add this app and sql data and also video to the readme file 
but can you see the issue of video sound if there is a problem

**Comment by elsayed85** [comment]
> i think there is no sound in video but we are so glade i will add this app and sql data and also video to the readme file
> but can you see the issue of video sound if there is a problem

okay I will solve it now

**Comment by elsayed85** [comment]
I will add some Reset API Requests in the future so anyone can use it 👍 
https://youtu.be/_jW3beDxppA

**Comment by Mohamed-Nagdy** [comment]
Ok thanks

**Comment by salamali** [comment]
شكرا جزيلا لك من القلب على هذه الفكرة الرائعة
اقترح عليك التعاون لتطويرها
بما يتناسب مع موقعي [القران الكريم](https://surahquran.com/)
و بانتظار رسالتك الكريمة
حفظك الله
