### ISSUE TITLE
السلام عليكم ورحمة الله  إذا ممكن كتب الحديث كاملة

### ISSUE THREAD

**Issue by zahsadz** [Mohamed-Nagdy/Hadith-Books-Json#9]
إذا ممكن رفع كتب الحديث كاملة علي جوجل درايف اما إذا كانت هذه النسخ التي عندك كما هي فلا بأس لاني لاحظت انها ناقصة  بعض الاحاديث.
ربما لان github لا يسمح باكثر من 50 ميقا

**Comment by Mohamed-Nagdy** [comment]
لا هي الاحاديث الموجودة كاملة او المتوفرة كلها هي المرفوعة اذا تحب تقدر تضيف الاحاديث الناقصة
